// Auto-generated by scan-factory.py at 2026-02-28 13:32:47
// Run: python3 scan-factory.py
// DO NOT EDIT — this file is overwritten on each scan
window.FACTORY_SCAN = [
  {
    "id": 1000,
    "name": "Ai Dictation Trademark Report",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Trademark Search Report: AI DICTATION / DICTATION / VOICE DI",
    "slug": "AI-DICTATION-trademark-report",
    "xcodeProj": ""
  },
  {
    "id": 1001,
    "name": "Mindvoice Trademark Report",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Trademark Search Report: MINDVOICE",
    "slug": "MINDVOICE-trademark-report",
    "xcodeProj": ""
  },
  {
    "id": 1002,
    "name": "Taxbuddy Trademark Report",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Trademark Search Report: TAXBUDDY",
    "slug": "TAXBUDDY-trademark-report",
    "xcodeProj": ""
  },
  {
    "id": 1003,
    "name": "Ai Dictation Listener",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "AI Dictation Listener \u2014 App Brief",
    "slug": "ai-dictation-listener",
    "xcodeProj": ""
  },
  {
    "id": 1004,
    "name": "Ai Meditation App",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "CalmFlow \u2014 Brand Package",
    "slug": "ai-meditation-app-brand",
    "xcodeProj": ""
  },
  {
    "id": 1005,
    "name": "Ai Meditation App",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "AI Meditation Companion \u2014 Product Brief",
    "slug": "ai-meditation-app-research",
    "xcodeProj": ""
  },
  {
    "id": 1006,
    "name": "Ambient Wellness",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Ambiently \u2014 Brand Brief",
    "slug": "ambient-wellness-brand",
    "xcodeProj": ""
  },
  {
    "id": 1007,
    "name": "Ambient Wellness",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Ambient Wellness \u2014 Product Brief",
    "slug": "ambient-wellness-research",
    "xcodeProj": ""
  },
  {
    "id": 1008,
    "name": "Atoms Habit Ai",
    "type": "app",
    "stage": "building",
    "agent": "ivy",
    "revenue": "Atoms \u2014 AI Habit Builder",
    "slug": "atoms-habit-ai-brief",
    "xcodeProj": ""
  },
  {
    "id": 1009,
    "name": "Atoms Habit",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Atoms \u2014 Brand Package",
    "slug": "atoms-habit-brand",
    "xcodeProj": ""
  },
  {
    "id": 1010,
    "name": "Babymind Ai",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "BabyMind AI Brand Guide",
    "slug": "babymind-ai-brand",
    "xcodeProj": ""
  },
  {
    "id": 1011,
    "name": "Babymind Ai",
    "type": "app",
    "stage": "building",
    "agent": "ivy",
    "revenue": "BabyMind AI \u2014 Smart Baby Tracker with AI Insights",
    "slug": "babymind-ai-research",
    "xcodeProj": ""
  },
  {
    "id": 1012,
    "name": "Calm Schedule",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "CalmSchedule \u2014 Product Brief",
    "slug": "calm-schedule",
    "xcodeProj": ""
  },
  {
    "id": 1013,
    "name": "Chatsey",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Chatsey \u2014 Brand Package",
    "slug": "chatsey-brand",
    "xcodeProj": ""
  },
  {
    "id": 1014,
    "name": "Checkmate",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "CHECKMATE \u2014 Brand Package",
    "slug": "checkmate-brand",
    "xcodeProj": ""
  },
  {
    "id": 1015,
    "name": "Checkmate",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "CHECKMATE \u2014 Product Brief",
    "slug": "checkmate-research",
    "xcodeProj": ""
  },
  {
    "id": 1016,
    "name": "Dailychief",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "DailyChief \u2014 Brand Package",
    "slug": "dailychief-brand",
    "xcodeProj": ""
  },
  {
    "id": 1017,
    "name": "Fileconverterpro",
    "type": "app",
    "stage": "building",
    "agent": "ivy",
    "revenue": "Product Brief: FileConverter Pro \u2014 Honest One-Time Price Fil",
    "slug": "fileconverterpro",
    "xcodeProj": ""
  },
  {
    "id": 1018,
    "name": "Finmind",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "FinMind \u2014 Brand Package",
    "slug": "finmind-brand",
    "xcodeProj": ""
  },
  {
    "id": 1019,
    "name": "Finmind",
    "type": "app",
    "stage": "approval",
    "agent": "vex",
    "revenue": "FinMind - Personal Finance AI",
    "slug": "finmind-research",
    "xcodeProj": "FinMind.xcodeproj",
    "hasDeployScript": true
  },
  {
    "id": 1020,
    "name": "Fitforge Ai",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "StrongForm AI \u2014 Brand Brief",
    "slug": "fitforge-ai-brand",
    "xcodeProj": ""
  },
  {
    "id": 1021,
    "name": "Fitforge Ai",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "FitForge AI \u2014 Personal AI Fitness Coach",
    "slug": "fitforge-ai-research",
    "xcodeProj": ""
  },
  {
    "id": 1022,
    "name": "Health Ai Tracker",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "VitalAI \u2014 Brand Package",
    "slug": "health-ai-tracker-brand",
    "xcodeProj": ""
  },
  {
    "id": 1023,
    "name": "Health Ai Tracker",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Health AI Tracker \u2014 Research Brief",
    "slug": "health-ai-tracker-research",
    "xcodeProj": ""
  },
  {
    "id": 1024,
    "name": "Heartsync Ai",
    "type": "app",
    "stage": "building",
    "agent": "ivy",
    "revenue": "In progress",
    "slug": "heartsync-ai",
    "xcodeProj": "HeartSync AI.xcodeproj"
  },
  {
    "id": 1025,
    "name": "Heartsync Ai",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "HeartSync AI \u2014 Relationship Coach in Your Pocket",
    "slug": "heartsync-ai-research",
    "xcodeProj": ""
  },
  {
    "id": 1026,
    "name": "Honey Rebrand",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "JOG \u2014 Brand Package (HONEY Replacement)",
    "slug": "honey-rebrand",
    "xcodeProj": ""
  },
  {
    "id": 1027,
    "name": "Honey",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "HONEY \u2014 Product Brief",
    "slug": "honey-research",
    "xcodeProj": ""
  },
  {
    "id": 1028,
    "name": "Life Organizer Openclaw",
    "type": "app",
    "stage": "building",
    "agent": "ivy",
    "revenue": "App Brief: LifeFlow \u2014 Organize Your Life with AI",
    "slug": "life-organizer-openclaw",
    "xcodeProj": ""
  },
  {
    "id": 1029,
    "name": "Lifeflow",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "In progress",
    "slug": "lifeflow",
    "xcodeProj": ""
  },
  {
    "id": 1030,
    "name": "Lifeflow",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "LifeFlow \u2014 Brand Package",
    "slug": "lifeflow-brand",
    "xcodeProj": ""
  },
  {
    "id": 1031,
    "name": "Melody Maker",
    "type": "app",
    "stage": "building",
    "agent": "ivy",
    "revenue": "In progress",
    "slug": "melody-maker",
    "xcodeProj": "MelodyMaker/MelodyMaker.xcodeproj",
    "hasDeployScript": true
  },
  {
    "id": 1032,
    "name": "Melody Maker",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Melody Maker \u2014 Brand Package",
    "slug": "melody-maker-brand",
    "xcodeProj": ""
  },
  {
    "id": 1033,
    "name": "Melody Maker",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Melody Maker \u2014 Product Brief",
    "slug": "melody-maker-research",
    "xcodeProj": ""
  },
  {
    "id": 1034,
    "name": "Mindfulcalendar",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "MindfulCalendar \u2014 Product Brief",
    "slug": "mindfulcalendar",
    "xcodeProj": ""
  },
  {
    "id": 1035,
    "name": "Mindfulmood",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "MindfulMood \u2014 Product Brief",
    "slug": "mindfulmood",
    "xcodeProj": ""
  },
  {
    "id": 1036,
    "name": "Mindvoice",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "MindVoice \u2014 Brand Package",
    "slug": "mindvoice-brand",
    "xcodeProj": ""
  },
  {
    "id": 1037,
    "name": "Mindvoice",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "MindVoice \u2014 AI Voice Journal for Mental Wellness",
    "slug": "mindvoice-research",
    "xcodeProj": ""
  },
  {
    "id": 1038,
    "name": "Openclaw Mainstream Positioning",
    "type": "app",
    "stage": "building",
    "agent": "ivy",
    "revenue": "Brief: OpenClaw Mainstream Positioning Research",
    "slug": "openclaw-mainstream-positioning",
    "xcodeProj": ""
  },
  {
    "id": 1039,
    "name": "Openclaw Positioning Final",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "OpenClaw Mainstream Positioning Research",
    "slug": "openclaw-positioning-research-FINAL",
    "xcodeProj": ""
  },
  {
    "id": 1040,
    "name": "Personal Super App",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Personal Super App \u2014 Research Brief",
    "slug": "personal-super-app-research",
    "xcodeProj": ""
  },
  {
    "id": 1041,
    "name": "Pixellock",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Product Brief: PixelLock \u2014 On-Device AI Photo Editor",
    "slug": "pixellock",
    "xcodeProj": ""
  },
  {
    "id": 1042,
    "name": "Private Ai Journal",
    "type": "app",
    "stage": "building",
    "agent": "ivy",
    "revenue": "Private AI Journal \u2014 Product Brief",
    "slug": "private-ai-journal",
    "xcodeProj": "Sanctuary.xcodeproj",
    "hasDeployScript": true
  },
  {
    "id": 1043,
    "name": "Samsung Notes Transfer",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Samsung Notes Transfer \u2014 App Brief",
    "slug": "samsung-notes-transfer",
    "xcodeProj": ""
  },
  {
    "id": 1044,
    "name": "Speakflow Ai",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "SpeakFlow AI \u2014 Conversational Language Learning",
    "slug": "speakflow-ai-research",
    "xcodeProj": ""
  },
  {
    "id": 1045,
    "name": "Studymind Ai",
    "type": "app",
    "stage": "building",
    "agent": "ivy",
    "revenue": "StudyMind AI \u2014 Product Brief",
    "slug": "studymind-ai",
    "xcodeProj": ""
  },
  {
    "id": 1046,
    "name": "Swiftlearn",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "SwiftLearn \u2014 Brand Package",
    "slug": "swiftlearn-brand",
    "xcodeProj": ""
  },
  {
    "id": 1047,
    "name": "Swiftlearn",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "SwiftLearn \u2014 AI Microlearning App",
    "slug": "swiftlearn-research",
    "xcodeProj": ""
  },
  {
    "id": 1048,
    "name": "Tax Buddy",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "TaxBuddy \u2014 Brand Package",
    "slug": "tax-buddy-brand",
    "xcodeProj": ""
  },
  {
    "id": 1049,
    "name": "Tax Buddy",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "TAXBUDDY \u2014 Product Brief",
    "slug": "tax-buddy-research",
    "xcodeProj": ""
  },
  {
    "id": 1050,
    "name": "Trademind",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "TradeMind \u2014 Brand Package",
    "slug": "trademind-brand",
    "xcodeProj": ""
  },
  {
    "id": 1051,
    "name": "Trademind",
    "type": "app",
    "stage": "approval",
    "agent": "vex",
    "revenue": "TradeMind - AI-Powered Trading Assistant",
    "slug": "trademind-research",
    "xcodeProj": ""
  },
  {
    "id": 1052,
    "name": "Tripgenie",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "TripGenie \u2014 Brand Package",
    "slug": "tripgenie-brand",
    "xcodeProj": ""
  },
  {
    "id": 1053,
    "name": "Tripgenie",
    "type": "app",
    "stage": "approval",
    "agent": "vex",
    "revenue": "TripGenie \u2014 AI Travel Planner",
    "slug": "tripgenie-research",
    "xcodeProj": ""
  },
  {
    "id": 1054,
    "name": "Vaultguard",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "VaultGuard \u2014 Brand Package",
    "slug": "vaultguard-brand",
    "xcodeProj": ""
  },
  {
    "id": 1055,
    "name": "Vaultguard",
    "type": "app",
    "stage": "approval",
    "agent": "vex",
    "revenue": "VaultGuard - iOS App Build",
    "slug": "vaultguard-research",
    "xcodeProj": ""
  },
  {
    "id": 1056,
    "name": "Verifid",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Product Brief: VerifID \u2014 Privacy-First Age Verification",
    "slug": "verifid",
    "xcodeProj": ""
  },
  {
    "id": 1057,
    "name": "Vocalog",
    "type": "app",
    "stage": "building",
    "agent": "ivy",
    "revenue": "5 Swift files",
    "slug": "vocalog",
    "xcodeProj": "Vocalog.xcodeproj",
    "hasDeployScript": true
  },
  {
    "id": 1058,
    "name": "Voice Journal Ai",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Voice Journal AI \u2014 Brand Package",
    "slug": "voice-journal-ai-brand",
    "xcodeProj": ""
  },
  {
    "id": 1059,
    "name": "Voice Journal Ai",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Voice Journal AI \u2014 Product Brief",
    "slug": "voice-journal-ai-research",
    "xcodeProj": ""
  },
  {
    "id": 1060,
    "name": "Voice Therapy Ai",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Voice Therapy AI \u2014 Product Brief",
    "slug": "voice-therapy-ai",
    "xcodeProj": ""
  },
  {
    "id": 1061,
    "name": "Voicewell",
    "type": "app",
    "stage": "building",
    "agent": "ivy",
    "revenue": "Voice Therapy AI \u2014 Brand Package",
    "slug": "voicewell-brand",
    "xcodeProj": "VoiceWell.xcodeproj",
    "hasDeployScript": true
  },
  {
    "id": 1062,
    "name": "Whispernotetaker",
    "type": "app",
    "stage": "new-idea",
    "agent": "luna",
    "revenue": "Product Brief: WhisperNotetaker \u2014 Privacy-First AI Meeting A",
    "slug": "whispernotetaker",
    "xcodeProj": ""
  }
];
